import {
    ArrowLeftOutlined,
    CalendarOutlined,
    ClockCircleOutlined,
    DeleteOutlined,
    EnvironmentOutlined,
    EyeInvisibleOutlined,
    EyeTwoTone,
    IdcardOutlined,
    LoadingOutlined,
    LockOutlined,
    LogoutOutlined,
    MailOutlined,
    PhoneOutlined,
    UploadOutlined,
    UserOutlined,
} from '@ant-design/icons';

export {
    ArrowLeftOutlined,
    CalendarOutlined,
    ClockCircleOutlined,
    DeleteOutlined,
    EnvironmentOutlined,
    EyeInvisibleOutlined,
    EyeTwoTone,
    IdcardOutlined,
    LoadingOutlined,
    LockOutlined,
    LogoutOutlined,
    MailOutlined,
    PhoneOutlined,
    UploadOutlined,
    UserOutlined,
};

export const Icons = {
    ArrowLeftOutlined,
    CalendarOutlined,
    ClockCircleOutlined,
    DeleteOutlined,
    EnvironmentOutlined,
    EyeInvisibleOutlined,
    EyeTwoTone,
    IdcardOutlined,
    LoadingOutlined,
    LockOutlined,
    LogoutOutlined,
    MailOutlined,
    PhoneOutlined,
    UploadOutlined,
    UserOutlined,
};
